- .github/workflows/tests.yml
- package-lock.json
- package.json
Configures tests to run on PRs to `main`.
closes #51
> run tests on CI

- app/index.js
- index.js
> rename app file

- package-lock.json
- package.json
This PR installs LESS, with no other build configuration.
> install LESS

- .github/CONTRIBUTING.md
This PR adds contributor guidelines in `.github/CONTRIBUTING.md`.
closes #30
> add contributing guidelines

- .github/workflows/deploy.yml
- README.md
- test/docs.unit.js
This PR updates the readme with some basic information about the project and some badges, and adds a test to make sure that the year in the suggested citation is up to date.
closes #33
> update readme and year test

- .github/CONTRIBUTING.md
closes #131
Adds information about the release process to the contributor doc.
> add release info

- layout/footer.hbs
- layout/footer.less
- package-lock.json
- package.json
Fixes styles for links in the footer.
> footer links

- package-lock.json
- package.json
Updates the design system to v0.6.0, which includes font sizing variables.
closes #174 (decided not to change the size of the main nav)
> design@0.6.0

- layout/footer.hbs
- layout/footer.less
Adds styling to the footer to accommodate small screens.
closes #173
> add footer styles for small screens

- .gitignore
- pages/404/404.hbs
- pages/404/404.test.js
- pages/500/500.hbs
- pages/About/About.test.js
- pages/Dictionaries/Dictionaries.test.js
- pages/Home/Home.test.js
- pages/Languages/Languages.test.js
- pages/Projects/Projects.test.js
closes #118 
Add tests to ensure each page title is correct. And, apply .link class to links in 404 and 500 pages.
> Test correct title

- app/index.js
- middleware/vary.js
- package-lock.json
- package.json
> Set the vary header

- build/convertLESS.js
- layout/footer.less
- layout/help-nav.less
- layout/index.hbs
- layout/index.less
- layout/main-nav.less
- layout/skip-link.hbs
- layout/skip-link.less
- package-lock.json
- package.json
- pages/Languages/Languages.less
closes #85 
Add a skip link. In addition, the import statement in the design system seems incorrect. After correcting it, the skip link can work correctly.
> Add skip-link

- pages/About/About.hbs
- pages/About/About.less
- pages/Dictionaries/Dictionaries.hbs
- pages/Dictionaries/Dictionaries.less
- pages/Home/Home.hbs
- pages/Home/Home.less
> Add styling for home, dictionary and about page

- build/convertLESS.js
- components/MultiLangString/MultiLangString.hbs
- components/MultiLangString/MultiLangString.less
- config/handlebars.js
- data/languages.yml
- pages/Design/Design.hbs
- pages/Design/Design.less
Adds a MultiLangString component.
closes #209
> MultiLangString

- layout/footer.less
- layout/help-nav.less
- layout/layout.less
- layout/main-nav.less
- layout/navbar.less
> Add dark mode styles to background, header, footer and help menu

- pages/404/404-server.js
- pages/404/404.test.js
- pages/500/500-server.js
- pages/500/500.test.js
- pages/About/About.test.js
- pages/Dictionaries/Dictionaries.test.js
- pages/Home/Home.test.js
- pages/Lexeme/Lexeme-server.js
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
- pages/Lexemes/Lexemes.test.js
- pages/ProjectLexemes/ProjectLexemes-server.js
- pages/Projects/Projects.test.js
This PR updates the content of the `<title>` element on existing pages.
closes #253
> page titles

- components/MultiLangString/MultiLangString.less
- pages/Language/Language.hbs
- pages/Language/Language.less
- pages/Language/Language.test.js
- pages/Project/Project.hbs
- pages/Project/Project.less
- pages/Project/Project.test.js
> Project Page & Language Page updates

- components/LanguagesTable/LanguagesTable.hbs
- pages/Projects/Projects-server.js
- pages/Projects/Projects.hbs
- pages/Projects/Projects.less
> Projects: display permissions

- layouts/main/app.less
- layouts/main/help-nav.less
> update flexbox-reset to v8.0.1

- layouts/main/app.less
- package-lock.json
- package.json
> fix missing focus styles

- pages/Lexeme/Lexeme.test.js
- pages/Lexeme/LexemeDetails-client.js
- pages/Lexeme/LexemeDetails.hbs
- pages/Lexeme/LexemeDetails.less
> Lexeme Details: keyboard navigation

- layouts/main/app.less
- pages/Lexeme/LexemeDetails-client.js
- pages/Lexeme/LexemeDetails.less
> Lexeme Details: responsive design

- pages/Lexeme/Lexeme-server.js
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
> Lexeme Details: date created + date modified + URL

- components/Cite/Cite.less
- components/Translation/Translation.less
- config/generic-style-rules-for-linguistics.csl
- data/index.js
- data/lexemes.yml
- data/references.bib
- package-lock.json
- package.json
- pages/Lexeme/Lexeme-server.js
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
- services/Database.js
> Lexeme Details: bibliography

- components/MultiOrthoTranscription/MultiOrthoTranscription.hbs
- components/Notes/Notes.hbs
- data/lexemes.yml
- data/references.bib
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
- pages/Lexemes/Lexemes.test.js
- pages/Project/Project.test.js
- services/Database.unit.js
> Lexeme Details: Citation Form

- data/lexemes.yml
- data/references.bib
- pages/Lexemes/Lexemes.test.js
- pages/Project/Project-server.js
- pages/Project/Project.test.js
- services/Database.unit.js
- Add sample Menominee data.
- Programmatically determine item counts in tests.
> sample data: Menominee

- components/LanguagesTable/LanguagesTable.hbs
- data/languages.yml
- pages/Languages/Languages-server.js
- pages/Languages/Languages.test.js
- utilities/permissions.js
> Lexeme Details: fix permissions column

- data/lexemes.yml
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
> Lexeme Details: template slot

- pages/Projects/Projects.hbs
> FIX: Projects: tooltips for privacy/permission icons

- components/LanguagesTable/LanguagesTable.hbs
- components/MultiLangString/MultiLangString.hbs
- components/MultiOrthoTranscription/MultiOrthoTranscription.hbs
- components/Transcription/Transcription.less
- config/handlebars.js
- data/languages.yml
- pages/Language/Language.hbs
- pages/Language/Language.test.js
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
> Lexeme Details: language information

- components/Headword/Headword.less
- config/handlebars.js
- data/languages.yml
- data/lexemes.yml
- data/references.bib
- pages/Languages/Languages.test.js
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
- ref.bib
> Lexeme Details: Cross-References

- components/DefinitionList/DefinitionList.less
- components/List/List.less
- data/lexemes.yml
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
> Lexeme Details: Forms List

- components/Details/Details.less
- components/MultiOrthoTranscription/MultiOrthoTranscription.hbs
- data/lexemes.yml
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
> Lexeme Details: form transcription

- data/lexemes.yml
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
> Lexeme Details: Form Sources

- components/Checkbox/Checkbox.less
- components/Details/Details.less
- data/lexemes.yml
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
> Lexeme Details: Abstract Form

- data/lexemes.yml
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
> Lexeme Details: Components

- data/lexemes.yml
- pages/Lexeme/Lexeme.hbs
> implement IDs for Lexeme Forms

- components/Headword/Headword.less
- data/languages.yml
- data/lexemes.yml
- pages/Languages/Languages.test.js
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
- services/Database.unit.js
> Lexeme Details: Etymology

- data/languages.yml
- data/lexemes.yml
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
> Lexeme Details: Form Reflexes

- data/index.js
- data/lexemes.yml
- pages/Lexeme/Lexeme-server.js
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.test.js
- pages/Lexemes/Lexemes.hbs
- pages/Lexemes/Lexemes.test.js
- services/Database.js
- services/Database.unit.js
- utilities/compareLemmas.js
> Unattested Forms

- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
> Lexeme Details: Senses List

- components/MultiLangString/MultiLangString.hbs
- config/handlebars.js
- data/lexemes.yml
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.test.js
> Lexeme Details: Sense Gloss

- data/lexemes.yml
- package.json
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
> Lexeme Details: Sense Category

- data/lexemes.yml
- pages/Language/Language.hbs
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Project/Project.hbs
- pages/Project/Project.less
closes #443
Also applies monospace font to appropriate project metadata fields.
> empty fields

- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.test.js
> Lexeme Details: use form IDs rather than indexes in HTML

- data/lexemes.yml
- data/references.bib
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
- pages/Lexemes/Lexemes.test.js
- reference.bib
- services/Database.unit.js
> Lexeme Details: Sense: Base Category

- data/lexemes.yml
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
> Lexeme Details: Sense: Inflection Class

- data/lexemes.yml
- data/references.bib
- pages/Lexeme/Lexeme.hbs
- pages/Lexeme/Lexeme.less
- pages/Lexeme/Lexeme.test.js
- reference.bib
> Lexeme Details: Sense: Semantic Class

- pages/Language/Language-server.js
- pages/Language/Language.hbs
- pages/Language/Language.test.js
> Language Projects

- pages/Lexeme/Lexeme-server.js
- pages/Lexeme/Lexeme.hbs
> NEW: Lexeme Projects

- .github/workflows/tests.yml
- .vscode/launch.json
- assets/images/search.svg
- assets/images/x-circle.svg
- components/Button/Button.less
- middleware/logger.js
- package-lock.json
- package.json
- pages/Lexemes/LanguageLexemes.js
- pages/Lexemes/Lexemes.hbs
- pages/Lexemes/Lexemes.less
- pages/Lexemes/Lexemes.test.js
- pages/Lexemes/ProjectLexemes.js
- services/database.js
> Lexemes: Quick Search (#292)

- pages/Project/Project.hbs
- pages/Project/Project.test.js
> Project Name

- app/index.js
- layouts/main/construction.hbs
- layouts/main/construction.less
- layouts/main/main.hbs
- layouts/main/main.less
> NEW: Construction Notice
